### ISSUE TITLE
packet_t should have options

### ISSUE THREAD

**Issue by 0xf104a** [Andrewerr/ddos2#3]
There is no way how to pass an options to interface module(e.g. mod_tcp). The fix will be done in @DedAzaMarks 's branch (`mod_tcp`). We decided to add hashtable to packet_t which will store option values.

**Comment by 0xf104a** [comment]
Fixed in branch `mod_tcp`

**Comment by DedAzaMarks** [comment]
was i finally fired?

**Comment by 0xf104a** [comment]
(Un)fortunately no. Fix of this issue was merged with branch `mod_udp` and thus issue was closed.

**Comment by DedAzaMarks** [comment]
Даров дрюзайНаписал тебе вопросик в элементе, но видимо потерялосьЕсли будет время глянь)Чмок
